---
- hosts: localhost
  vars_files: 
    - users.yml
  vars: 
    - user_password: "{{ lookup('ansible.builtin.password', 'password-' + item['name'], encrypt='sha512_crypt') }}"
  tasks: 
  - ansible.builtin.user: 
      name: "{{ item['name'] }}"
      uid: "{{ item['uid'] }}"
      comment: "{{ item.first | capitalize }} {{ item.middle | capitalize }} {{ item.last | capitalize }}"
      password: 
      state: present 
    loop: "{{ users }}"
